version: '3.7'

services:

 mongo:
   container_name: mongo
   ports:
    - 27017:27017
   image: mongo:latest
   volumes:
    - ./data/mongo:/data/db


 app:
   container_name: node_app
   working_dir: /app
   restart: always
   build: .
   volumes:
    - ./data/app:/data/app
   ports:
    -  51005:51005
   command: 'node server.js'

 db:
   container_name: mysql 
   image: mysql:latest
   volumes:
    - ./data/mysql:/data/mysql
   restart: always
   ports:
    - 3306:3306
   environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mysql
      MYSQL_USER: mateen
      MYSQL_PASSWORD: password
   
   healthcheck: 
    test: ["CMD", "curl", "-f", "localhost"]
    interval: 30s
    timeout: 5s
    retries: 1
    start_period: 30s

volumes: 
  data:
       