version: '3.7'

services:

 mongo:
   ports:
    - 27017:27017
   image: mongo:latest
   volumes:
    - ./data/mongo:/data/db


 app:
   image: node:10
   working_dir: /home/node/app
   restart: always
   volumes:
    - ./data/app:/home/node/app
   ports:
    -  51005:51005
   command: 'node server.js'

 db: 
   image: mysql:latest
   volumes:
    - ./data/mysql:/data/mysql
   restart: always
   ports:
    - 3306:3306
   environment:
     MYSQL_ROOT_PASSWORD:  password
     MYSQL_USER: root 


volumes: 
  data:
       